version: 1
formatters:
  verbose:
    format: '%(asctime)s - %(name)s - %(levelname)s @ %(module)s - %(funcName)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: verbose
    stream: ext://sys.stdout
  verbose_filehandler:
    class: logging.FileHandler
    formatter: verbose
    filename: verbose.log
    mode: 'w'
loggers:
  verboseLogger:
    level: DEBUG
    handlers: [verbose_filehandler]
root:
  level: DEBUG
  handlers: [console]