version: 1
disable_existing_loggers: False
formatters:
  brief:
    format: '%(asctime)s - %(message)s'
#    format: '%(asctime)s - %(name)s - %(levelname)s @ %(module)s - %(funcName)s - %(message)s'
  verbose:
    format: '%(asctime)s - %(name)s - %(levelname)s @ %(module)s - %(funcName)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: brief
    stream: ext://sys.stdout
  verbose_filehandler:
    class: logging.FileHandler
    formatter: verbose
    filename: verbose.log
    mode: 'a'
    encoding: 'utf-8'
loggers:
  verboseLogger:
    level: DEBUG
    handlers: [verbose_filehandler]
root:
  level: INFO
  handlers: [console]